[theme]
base="light"

[server]
folderWatchBlacklist = ["__pycache__", ".git", ".venv", "venv", "env", "artifacts", "runs", "mlruns"]

runOnSave = false

fileWatcherType = "none"

headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 512
maxMessageSize = 512
